repository: dynamsoft-docs/faq
repositoryUrl: https://github.com/dynamsoft-docs/faq/blob/main
docFullPath: https://www.dynamsoft.com/faq
firstLevelUrl: /faq
docHomePage: /faq/
faq-center: /faq/
product-page-url: https://www.dynamsoft.com/faq
searchIndexName: Crawler-FAQ-Docs
searchNeedFilter: true

product-name: /faq/
product-title: Dynamsoft FAQ

dbr-faq: /faq/barcode-reader
dbr-mobile-faq: /faq/barcode-reader/mobile
dbr-server-faq: /faq/barcode-reader/server
dbr-web-faq: /faq/barcode-reader/web
dbr-license-faq: /faq/barcode-reader/license
dbr-general-faq: /faq/barcode-reader/general
mrz-faq: /faq/mrz-scanner
mrz-license-faq: /faq/mrz-scanner/license
mrz-general-faq: /faq/mrz-scanner/general

useVersionTree: true

assets: /faq/assets/
dbr_server_assets: /faq/barcode-reader/server/assets/
dbr_web_assets: /faq/barcode-reader/web/assets/
dbr_mobile_assets: /faq/barcode-reader/mobile/assets/
edit_icon: /faq/assets/img-icon/edit-icon.png
smile_icon: /faq/assets/img-icon/icon-smile.png
sad_icon: /faq/assets/img-icon/icon-sad.png

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false
  - scope:
      path: "barcode-reader/mobile/capabilities"
    values:
      highlightMenu: "/faq/barcode-reader/mobile/index.html#capabilities"
  - scope:
      path: "barcode-reader/mobile/configuration"
    values:
      highlightMenu: "/faq/barcode-reader/mobile/index.html#configuration"
  - scope:
      path: "barcode-reader/mobile/cross-platform"
    values:
      highlightMenu: "/faq/barcode-reader/mobile/index.html#cross-platform"
  - scope:
      path: "barcode-reader/mobile/debug"
    values:
      highlightMenu: "/faq/barcode-reader/mobile/index.html#debug"
  - scope:
      path: "barcode-reader/mobile/scan-setting"
    values:
      highlightMenu: "/faq/barcode-reader/mobile/index.html#scan-setting"
  - scope:
      path: "barcode-reader/mobile/simulator"
    values:
      highlightMenu: "/faq/barcode-reader/mobile/index.html#simulator"
  - scope:
      path: "barcode-reader/server/configuration"
    values:
      highlightMenu: "/faq/barcode-reader/server/index.html#configuration"
  - scope:
      path: "barcode-reader/web/scan-setting"
    values:
      highlightMenu: "/faq/barcode-reader/web/index.html#scan-setting"
  - scope:
      path: "barcode-reader/web/camera"
    values:
      highlightMenu: "/faq/barcode-reader/web/index.html#camera"
  - scope:
      path: "barcode-reader/web/capabilities"
    values:
      highlightMenu: "/faq/barcode-reader/web/index.html#capabilities"
  - scope:
      path: "barcode-reader/web/configuration"
    values:
      highlightMenu: "/faq/barcode-reader/web/index.html#configuration"
  - scope:
      path: "barcode-reader/web/ui-customization"
    values:
      highlightMenu: "/faq/barcode-reader/web/index.html#ui-customization"
  - scope:
      path: "barcode-reader/web/debug"
    values:
      highlightMenu: "/faq/barcode-reader/web/index.html#debug"

url: https://www.dynamsoft.com # sitemap root
baseurl: /faq